# coding=utf-8

from setuptools import setup, find_packages
import os


setup (
    name = "sync_lily_from_timescaledb_to_bigquery",
    version = "0.0.1",
    author = "pxx",
    author_email = "pxx@starboardventures.io",
    description = "Synchronize lily tables from TimescaleDB to BigQuery for PL.",
    long_description = open(os.path.join(os.path.dirname(__file__), "README.md")).read(),
    long_description_content_type = "text/markdown",
    url = "https://github.com/starboard-ventures/sync_lily_to_bigquery",
    packages = find_packages(),
    include_package_data=True,
    package_data = {"": ["*.ini"]},
    install_requires = open(os.path.join(os.path.dirname(__file__), "requirements.txt")).read().splitlines(),
    entry_points = {
        "console_scripts": [
            "dummy = sync_lily_from_timescaledb_to_bigquery.main:proc_dummy",
            "actor_codes = sync_lily_from_timescaledb_to_bigquery.main:proc_actor_codes",
            "actor_events = sync_lily_from_timescaledb_to_bigquery.main:proc_actor_events",
            "actor_methods = sync_lily_from_timescaledb_to_bigquery.main:proc_actor_methods",
            "actor_states = sync_lily_from_timescaledb_to_bigquery.main:proc_actor_states",
            "actors = sync_lily_from_timescaledb_to_bigquery.main:proc_actors",
            "block_headers = sync_lily_from_timescaledb_to_bigquery.main:proc_block_headers",
            "block_messages = sync_lily_from_timescaledb_to_bigquery.main:proc_block_messages",
            "block_parents = sync_lily_from_timescaledb_to_bigquery.main:proc_block_parents",
            "builtin_actor_events = sync_lily_from_timescaledb_to_bigquery.main:proc_builtin_actor_events",
            "chain_consensus = sync_lily_from_timescaledb_to_bigquery.main:proc_chain_consensus",
            "chain_economics = sync_lily_from_timescaledb_to_bigquery.main:proc_chain_economics",
            "chain_powers = sync_lily_from_timescaledb_to_bigquery.main:proc_chain_powers",
            "chain_rewards = sync_lily_from_timescaledb_to_bigquery.main:proc_chain_rewards",
            "data_cap_balances = sync_lily_from_timescaledb_to_bigquery.main:proc_data_cap_balances",
            "derived_gas_outputs = sync_lily_from_timescaledb_to_bigquery.main:proc_derived_gas_outputs",
            "drand_block_entries = sync_lily_from_timescaledb_to_bigquery.main:proc_drand_block_entries",
            "fevm_actor_dumps = sync_lily_from_timescaledb_to_bigquery.main:proc_fevm_actor_dumps",
            "fevm_actor_stats = sync_lily_from_timescaledb_to_bigquery.main:proc_fevm_actor_stats",
            "fevm_block_headers = sync_lily_from_timescaledb_to_bigquery.main:proc_fevm_block_headers",
            "fevm_contracts = sync_lily_from_timescaledb_to_bigquery.main:proc_fevm_contracts",
            "fevm_receipts = sync_lily_from_timescaledb_to_bigquery.main:proc_fevm_receipts",
            "fevm_traces = sync_lily_from_timescaledb_to_bigquery.main:proc_fevm_traces",
            "fevm_transactions = sync_lily_from_timescaledb_to_bigquery.main:proc_fevm_transactions",
            "id_addresses = sync_lily_from_timescaledb_to_bigquery.main:proc_id_addresses",
            "internal_messages = sync_lily_from_timescaledb_to_bigquery.main:proc_internal_messages",
            "internal_parsed_messages = sync_lily_from_timescaledb_to_bigquery.main:proc_internal_parsed_messages",
            "market_deal_proposals = sync_lily_from_timescaledb_to_bigquery.main:proc_market_deal_proposals",
            "market_deal_states = sync_lily_from_timescaledb_to_bigquery.main:proc_market_deal_states",
            "message_gas_economy = sync_lily_from_timescaledb_to_bigquery.main:proc_message_gas_economy",
            "message_params = sync_lily_from_timescaledb_to_bigquery.main:proc_message_params",
            "messages = sync_lily_from_timescaledb_to_bigquery.main:proc_messages",
            "miner_actor_dumps = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_actor_dumps",
            "miner_beneficiaries = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_beneficiaries",
            "miner_current_deadline_infos = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_current_deadline_infos",
            "miner_fee_debts = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_fee_debts",
            "miner_infos = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_infos",
            "miner_locked_funds = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_locked_funds",
            "miner_pre_commit_infos = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_pre_commit_infos",
            "miner_pre_commit_infos_v9 = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_pre_commit_infos_v9",
            "miner_sector_deals = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_sector_deals",
            "miner_sector_deals_v2 = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_sector_deals_v2",
            "miner_sector_events = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_sector_events",
            "miner_sector_infos = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_sector_infos",
            "miner_sector_infos_v7 = sync_lily_from_timescaledb_to_bigquery.main:proc_miner_sector_infos_v7",
            "multisig_approvals = sync_lily_from_timescaledb_to_bigquery.main:proc_multisig_approvals",
            "multisig_transactions = sync_lily_from_timescaledb_to_bigquery.main:proc_multisig_transactions",
            "parsed_messages = sync_lily_from_timescaledb_to_bigquery.main:proc_parsed_messages",
            "power_actor_claims = sync_lily_from_timescaledb_to_bigquery.main:proc_power_actor_claims",
            "receipts = sync_lily_from_timescaledb_to_bigquery.main:proc_receipts",
            "surveyed_miner_protocols = sync_lily_from_timescaledb_to_bigquery.main:proc_surveyed_miner_protocols",
            "surveyed_peer_agents = sync_lily_from_timescaledb_to_bigquery.main:proc_surveyed_peer_agents",
            "unsynced_block_headers = sync_lily_from_timescaledb_to_bigquery.main:proc_unsynced_block_headers",
            "verified_registry_claims = sync_lily_from_timescaledb_to_bigquery.main:proc_verified_registry_claims",
            "verified_registry_verified_clients = sync_lily_from_timescaledb_to_bigquery.main:proc_verified_registry_verified_clients",
            "verified_registry_verifiers = sync_lily_from_timescaledb_to_bigquery.main:proc_verified_registry_verifiers",
            "vm_messages = sync_lily_from_timescaledb_to_bigquery.main:proc_vm_messages"
        ],
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Console",
        "Topic :: Utilities",
        "Programming Language :: Python :: 3.10",
        "Intended Audience :: Developers"
    ]
)

